// comments actions
export const FETCHING_COMMENTS = 'FETCHING_COMMENTS'
export const FETCHING_COMMENTS_ERROR = 'FETCHING_COMMENTS_ERROR'
export const FETCHING_COMMENTS_SUCCESS = 'FETCHING_COMMENTS_SUCCESS'
export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR'
export const REMOVE_COMMENT = 'REMOVE_COMMENT'

// feed actions
export const SETTING_FEED_LISTENER = 'SETTING_FEED_LISTENER'
export const SETTING_FEED_LISTENER_ERROR = 'SETTING_FEED_LISTENER_ERROR'
export const SETTING_FEED_LISTENER_SUCCESS = 'SETTING_FEED_LISTENER_SUCCESS'
export const ADD_NEW_GAME_ID_TO_FEED = 'ADD_NEW_GAME_ID_TO_FEED'
export const RESET_NEW_GAMES_AVAILABLE = 'RESET_NEW_GAMES_AVAILABLE'

// games actions
export const FETCHING_GAME = 'FETCHING_GAME'
export const FETCHING_GAME_ERROR = 'FETCHING_GAME_ERROR'
export const FETCHING_GAME_SUCCESS = 'FETCHING_GAME_SUCCESS'
export const ADD_GAME = 'ADD_GAME'
export const ADD_MULTIPLE_GAMES = 'ADD_MULTIPLE_GAMES'
export const REMOVE_FETCHING = 'REMOVE_FETCHING'

// listeners actions
export const ADD_LISTENER = 'ADD_LISTENER'

// navigation actions
export const TOGGLE_MENU = 'TOGGLE_MENU'

// new game actions
export const UPDATE_SESSION_TITLE = 'UPDATE_SESSION_TITLE'
export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT'
export const QUERYING_GAMES = 'QUERYING_GAMES'
export const QUERYING_GAMES_SUCCESS = 'QUERYING_GAMES_SUCCESS'
export const QUERYING_GAMES_ERROR = 'QUERYING_GAMES_ERROR'
export const UPDATE_SELECTED_GAME = 'UPDATE_SELECTED_GAME'
export const ADD_PLAYER = 'ADD_PLAYER'
export const ADD_MAIN_PLAYER = 'ADD_MAIN_PLAYER'
export const UPDATE_PLAYER = 'UPDATE_PLAYER'
export const SAVING_GAME = 'SAVING_GAME'
export const SAVING_GAME_SUCCESS = 'SAVING_GAME_SUCCESS'
export const SAVING_GAME_ERROR = 'SAVING_GAME_ERROR'
export const CLEAR_NEW_GAME_FORM = 'CLEAR_NEW_GAME_FORM'
export const UPDATE_IS_WIN = 'UPDATE_IS_WIN'
export const UPDATE_COMMENTS = 'UPDATE_COMMENTS'
export const REMOVE_PLAYER = 'REMOVE_PLAYER'

// users actions
export const AUTH_USER = 'AUTH_USER'
export const UNAUTH_USER = 'UNAUTH_USER'
export const FETCHING_USER = 'FETCHING_USER'
export const FETCHING_USER_FAILURE = 'FETCHING_USER_FAILURE'
export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS'
export const REMOVE_FETCHING_USER = 'REMOVE_FETCHING_USER'

// users games actions
export const FETCHING_USERS_GAMES = 'FETCHING_USERS_GAMES'
export const FETCHING_USERS_GAMES_ERROR = 'FETCHING_USERS_GAMES_ERROR'
export const FETCHING_USERS_GAMES_SUCCESS = 'FETCHING_USERS_GAMES_SUCCESS'
export const ADD_SINGLE_USERS_GAME = 'ADD_SINGLE_USERS_GAME'
